# Generated by Django 6.0.1 on 2026-01-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_unlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='unlike',
            new_name='unlikes',
        ),
    ]
