# Generated by Django 6.0.1 on 2026-01-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tag',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='views_count',
            new_name='views',
        ),
    ]
