# Generated by Django 6.0.1 on 2026-01-30 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_postreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postreport',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='postreport',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
