# Generated by Django 6.0.1 on 2026-01-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_rename_created_postreport_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PostReport',
        ),
    ]
