# Generated by Django 6.0.1 on 2026-01-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_post_reported_delete_postreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reported',
        ),
    ]
